### ISSUE TITLE
Support for blocknewsletter subscriptions

### ISSUE THREAD

**Issue by Casper-O** [xportde/campaignmonitor#1]
Would be with support for blocknewsletter, so customers that sign up via the form is also exported to campaign monitor

**Comment by pgml** [comment]
I finally had the time to implement the blocknewsletter support.
I'd recommend not to test this with your productive shop. 
Create a second list and a duplicate of your shop.

If you update, you need to hit the »Save Options« button first. There's a new custom field for the shop id that will be sent to cm (it is needed if the customer is unsubscribing via campaign monitor, so that prestashop knows exactly who to unsubscribe).
Furthermore you need to hook the module into the prestashop header (BO > »Modules and Services > »Positions« > »Transplant a module«).
No need for that if you do a fresh install.
**_edit: Unsubscribing within CM will not affect the duplicate shop but your productive shop, unless you uninstall and then reinstall the module so that the web hook url is updated because this url is bound to the api data.
Do the same in your productive shop if you are finished testing.**_

To export those who has already subscribed to the blocknewsletter, you have to hit the »export« button again. It could take a while since it will update/synchronise the whole customer database to campaign monitor.

**Comment by Casper-O** [comment]
It seems to work as it should with the recent version
